name: flutter_validators
description: Validator utilities for flutter
version: 0.0.1
author: Ian Luca de Godoy Serpa <ian.naph@gmail.com>
homepage: https://github.com/ianldgs/flutter_validators

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  test: "^0.12.38"
  mockito: "^2.2.3"
  